apiVersion: apps/v1
kind: Deployment
metadata:
  name: pacs-backend
  labels:
    app: pacs-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pacs-backend
  template:
    metadata:
      labels:
        app: pacs-backend
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - pacs-backend
              topologyKey: "kubernetes.io/hostname"
      containers:
      - name: pacs-api
        image: us-central1-docker.pkg.dev/mwakilishi-1770258957/pacs-repo/pacs-api:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        env:
        # This securely pulls the URL from the secret
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: cloudsql-db-credentials
              key: database_url
---
apiVersion: v1
kind: Service
metadata:
  name: pacs-backend-service
spec:
  type: ClusterIP
  selector:
    app: pacs-backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000