apiVersion: apps/v1
kind: Deployment
metadata:
  name: pacs-frontend
  labels:
    app: pacs-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pacs-frontend
  template:
    metadata:
      labels:
        app: pacs-frontend
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - pacs-frontend
              topologyKey: "kubernetes.io/hostname"
      containers:
      - name: pacs-ui
        image: us-central1-docker.pkg.dev/mwakilishi-1770258957/pacs-repo/pacs-ui:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: BACKEND_URL
          # Updated to match the service name we found with kubectl
          value: "http://pacs-backend-service:8000"
---
apiVersion: v1
kind: Service
metadata:
  name: pacs-frontend-service
spec:
  type: ClusterIP
  selector:
    app: pacs-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80