apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pacs-api-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: gce
    networking.gke.io/managed-certificates: pacs-ivanova-cert
    kubernetes.io/ingress.global-static-ip-name: k8s2-fr-4pun04rj-default-pacs-api-ingress-dfn5968q
    kubernetes.io/ingress.allow-http: "false" 
spec:
  rules:
  - host: drupal.ivanova.tech
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: drupal-service
            port:
              number: 80
  - host: pacs.ivanova.tech
    http:
      paths:
      # --- BACKEND DATA ROUTE ---
      # This captures /api/patients, /api/studies, etc.
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: pacs-backend-service
            port:
              number: 8000
      # --- FRONTEND UI ROUTE ---
      # This now correctly captures /patients for the Angular UI
      - path: /
        pathType: Prefix
        backend:
          service:
            name: pacs-frontend-service
            port:
              number: 80
  - host: pacs-api.ivanova.tech
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: pacs-backend-service
            port:
              number: 8000