apiVersion: apps/v1
kind: Deployment
metadata:
  name: pacs-api
  labels:
    app: pacs-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pacs-api
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: pacs-api
    spec:
      containers:
      - name: pacs-api
        image: gcr.io/mwakilishi-1770258957/pacs-api:latest
        ports:
        - containerPort: 8000
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - pacs-api
            topologyKey: "kubernetes.io/hostname"
