apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pacs-api-ingress
  annotations:
    # 1. This is the correct key for ManagedCertificate objects
    networking.gke.io/managed-certificates: "pacs-ivanova-cert,apps-cert"
    # 2. Your existing Static IP
    kubernetes.io/ingress.global-static-ip-name: "k8s2-fr-4pun04rj-default-pacs-api-ingress-dfn5968q"
    # 3. Tells GKE to use the Google Cloud Load Balancer
    kubernetes.io/ingress.class: "gce"
spec:
  rules:
  - host: pacs.ivanova.tech
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: pacs-backend-service
            port:
              number: 8000
      - path: /
        pathType: Prefix
        backend:
          service:
            name: pacs-frontend-service
            port:
              number: 80
  - host: drupal.ivanova.tech
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: drupal-service
            port:
              number: 80