apiVersion: v1
kind: Service
metadata:
  name: pacs-api-service
  namespace: default
spec:
  selector:
    app: pacs-api
  ports:
    - protocol: TCP
      port: 80        # what Ingress talks to
      targetPort: 8000  # FastAPI container port
  type: ClusterIP
